### ISSUE TITLE
Ability to write to lastpass vault

### ISSUE THREAD

**Issue by hinjo** [detunized/lastpass-sharp#4]
Are there any plans to add support for writing credentials to LastPass vault, in this otherwise great LastPass C# port, in addition to reading?
Would be great to have write abilities to the attributes of the vault that are available for reading today.

**Comment by detunized** [comment]
Nope, sorry, there are no plans currently. It complicates the library significantly and I currently have no use case for that. There's the [lastpass-cli](https://githib.com/lastpass/lastpass-cli) project that does the writing. It's not a .NET library though.

**Comment by hinjo** [comment]
Hi there again, I guess you still have no plans of introducing writing ability to LastPass, but I was wondering where I could start if I want to try to introduce this functionality.. Where to start kind off? I have been looking through your code to see how the calls are made but I need kind of know where to look for the syntax of these lastpass http calls...

**Comment by detunized** [comment]
I did all this by reverse engineering the web vault and the Android app. There's no good place to look for the HTTP calls. You need to study the JavaScript code and inspect the network calls made by it. 

You can look at the lastpass CLI source code, but keep in mind that it's GPL licensed and it is not compatible with the closed sourced applications or with more permissive licenses like the MIT license used in this project.
