### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by vaibhavrja** [detunized/lastpass-sharp#5]
I download the code and change the credentials but it gives me Lastpass.loginException and when I try to add the code in my main file 
using LastPass;

var vault = Vault.Create(username, password);
foreach (var i in vault.Accounts)
    Console.WriteLine("{0}: {1}, {2}", i.Name, i.Username, i.Password);
It gives me an error that create method requires 3 parameters.

**Comment by detunized** [comment]
This library is no longer supported. I guess I should have put it in the README. Please check https://github.com/detunized/password-manager-access for the new library that is actively supported.

**Comment by vaibhavrja** [comment]
Thankyou so much for the help @detunized .
